/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author josevargas
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        openfile = false;
        ArchivoAbierto();
        this.setLocationRelativeTo(null);
        lls.setSelected(true);
        archivo_nuevo = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDCrearCampo = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonGuardarCampo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        llaveps = new javax.swing.JLabel();
        llp = new javax.swing.JRadioButton();
        lls = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDModificarCampo = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        PopMenuModificar = new javax.swing.JPopupMenu();
        jMenuModificarCampo = new javax.swing.JMenuItem();
        jDBorrarRegistro = new javax.swing.JDialog();
        jButtonBorrarRegistro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCBRegistros = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDModificar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NuevoNombre = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nombreactual = new javax.swing.JLabel();
        jDBorrarCampo = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        ck = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevoArchivo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuCampos = new javax.swing.JMenu();
        jMenuItemNuevoCampo = new javax.swing.JMenuItem();
        jMenuItemListarCampos = new javax.swing.JMenuItem();
        jMenuItemModificarCampos = new javax.swing.JMenuItem();
        jMenuItemBorrarCampos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre del Campo:");

        jLabel2.setText("Campo Llave:");

        jButtonGuardarCampo.setText("Guardar Campo");
        jButtonGuardarCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarCampoMouseClicked(evt);
            }
        });

        jLabel3.setText("Tipo de Campo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Int", "Char", "Long" }));

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setText("Longitud del Campo:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        buttonGroup1.add(llp);
        llp.setText("LLave Principal");

        buttonGroup1.add(lls);
        lls.setText("LLave Secundaria");

        javax.swing.GroupLayout jDCrearCampoLayout = new javax.swing.GroupLayout(jDCrearCampo.getContentPane());
        jDCrearCampo.getContentPane().setLayout(jDCrearCampoLayout);
        jDCrearCampoLayout.setHorizontalGroup(
            jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDCrearCampoLayout.createSequentialGroup()
                .addGap(40, 214, Short.MAX_VALUE)
                .addComponent(jButtonGuardarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jDCrearCampoLayout.createSequentialGroup()
                .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDCrearCampoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDCrearCampoLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(jDCrearCampoLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDCrearCampoLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(57, 57, 57))
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDCrearCampoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(llaveps, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDCrearCampoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jDCrearCampoLayout.createSequentialGroup()
                                .addComponent(llp)
                                .addGap(29, 29, 29)
                                .addComponent(lls)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDCrearCampoLayout.setVerticalGroup(
            jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDCrearCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(llaveps, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llp)
                    .addComponent(lls))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jDCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("Modificar Campo");

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDModificarCampoLayout = new javax.swing.GroupLayout(jDModificarCampo.getContentPane());
        jDModificarCampo.getContentPane().setLayout(jDModificarCampoLayout);
        jDModificarCampoLayout.setHorizontalGroup(
            jDModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDModificarCampoLayout.createSequentialGroup()
                .addGroup(jDModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDModificarCampoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDModificarCampoLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jDModificarCampoLayout.setVerticalGroup(
            jDModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDModificarCampoLayout.createSequentialGroup()
                .addGroup(jDModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDModificarCampoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDModificarCampoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenuModificarCampo.setText("jMenuItem16");
        jMenuModificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarCampoActionPerformed(evt);
            }
        });
        PopMenuModificar.add(jMenuModificarCampo);

        jButtonBorrarRegistro.setText("Borrar Registro");
        jButtonBorrarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBorrarRegistroMouseClicked(evt);
            }
        });

        jLabel9.setText("Elija el registro a borrar:");

        jButton2.setText("Regresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setText("Borrar Registro");

        javax.swing.GroupLayout jDBorrarRegistroLayout = new javax.swing.GroupLayout(jDBorrarRegistro.getContentPane());
        jDBorrarRegistro.getContentPane().setLayout(jDBorrarRegistroLayout);
        jDBorrarRegistroLayout.setHorizontalGroup(
            jDBorrarRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDBorrarRegistroLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jDBorrarRegistroLayout.createSequentialGroup()
                .addGroup(jDBorrarRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDBorrarRegistroLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel9))
                    .addGroup(jDBorrarRegistroLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jDBorrarRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jCBRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDBorrarRegistroLayout.setVerticalGroup(
            jDBorrarRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDBorrarRegistroLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jCBRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jDBorrarRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jLabel8.setText("Modificar Nombre Campo");

        nom.setText("Nombre Actual:");

        jLabel10.setText("Nuevo Nombre:");

        NuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoNombreActionPerformed(evt);
            }
        });

        jButton3.setText("Completar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(nom)
                            .addComponent(NuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(nombreactual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton3)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreactual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDModificarLayout = new javax.swing.GroupLayout(jDModificar.getContentPane());
        jDModificar.getContentPane().setLayout(jDModificarLayout);
        jDModificarLayout.setHorizontalGroup(
            jDModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDModificarLayout.setVerticalGroup(
            jDModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setText("Eliminar Campo");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton5.setText("Borrar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jDBorrarCampoLayout = new javax.swing.GroupLayout(jDBorrarCampo.getContentPane());
        jDBorrarCampo.getContentPane().setLayout(jDBorrarCampoLayout);
        jDBorrarCampoLayout.setHorizontalGroup(
            jDBorrarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDBorrarCampoLayout.setVerticalGroup(
            jDBorrarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("EE2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setText("LLave Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ck, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ck)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevoArchivo.setText("Nuevo Archivo");
        jMenuItemNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoArchivoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevoArchivo);

        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem1);

        jMenuItem2.setText("Salvar Archivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem2);

        jMenuItem3.setText("Cerrar Archivo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem4);

        jMenuBar1.add(jMenuArchivo);

        jMenuCampos.setText("Campos");

        jMenuItemNuevoCampo.setText("Agregar Campos");
        jMenuItemNuevoCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemNuevoCampoMouseClicked(evt);
            }
        });
        jMenuItemNuevoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoCampoActionPerformed(evt);
            }
        });
        jMenuCampos.add(jMenuItemNuevoCampo);

        jMenuItemListarCampos.setText("Listar Campos");
        jMenuItemListarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarCamposActionPerformed(evt);
            }
        });
        jMenuCampos.add(jMenuItemListarCampos);

        jMenuItemModificarCampos.setText("Modificar Campos");
        jMenuItemModificarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarCamposActionPerformed(evt);
            }
        });
        jMenuItemModificarCampos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItemModificarCamposKeyPressed(evt);
            }
        });
        jMenuCampos.add(jMenuItemModificarCampos);

        jMenuItemBorrarCampos.setText("Borrar Campos");
        jMenuItemBorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarCamposActionPerformed(evt);
            }
        });
        jMenuCampos.add(jMenuItemBorrarCampos);

        jMenuBar1.add(jMenuCampos);

        jMenu1.setText("Registros");

        jMenuItem7.setText("Introducir Registros");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Modificar Registros");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Buscar Registros");
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Borrar Registros");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("Listar Registros");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Indices");

        jMenuItem12.setText("Crear Indices");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Re Indexar Archivos");
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estandarización");

        jMenuItem14.setText("Exportar Excel");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("Exportar XML con Schema");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemNuevoCampoMouseClicked
        jDCrearCampo.setModal(true);
        jDCrearCampo.pack();
        jDCrearCampo.setLocationRelativeTo(null);
        jDCrearCampo.setVisible(true);
    }//GEN-LAST:event_jMenuItemNuevoCampoMouseClicked

    private void jButtonGuardarCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarCampoMouseClicked
        if (jTextField1.toString() != "") {
            String nombre = jTextField1.getText();
            String tipo = jComboBox1.getSelectedItem().toString();
            int longitud = (Integer) jSpinner1.getValue();
            boolean campo_llave = false;
            if (llp.isSelected()) {
                if (archivo.isLlaveprimaria() == false) {
                    campo_llave = true;
                    archivo.setLlaveprimaria(true);
                    ck.setText(nombre);
                    archivo.setNombrellave(nombre);
                } else {
                    JOptionPane.showMessageDialog(null, "Había seleccionado anteriormente un campo como llave principal");
                    int aux = JOptionPane.showConfirmDialog(null, "Desea cambiar la llave principal a este campo?",
                            "Cambiar llave principal", JOptionPane.INFORMATION_MESSAGE);
                    if (aux == JOptionPane.YES_OPTION) {
                        campo_llave = true;
                        ck.setText(nombre);
                        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
                            archivo.getListaCampos().get(i).setLlave_primaria(false);
                        }

                    }
                }
            }
            Campo campo = new Campo(nombre, tipo, longitud, campo_llave);
            archivo.addCampo(campo);
            JOptionPane.showMessageDialog(null, "El campo fue creado exitósamente");
            jTextField1.setText("");
            jDCrearCampo.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un nombre para el campo");
        }
    }//GEN-LAST:event_jButtonGuardarCampoMouseClicked

    private void jMenuItemNuevoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoCampoActionPerformed
        if (archivo.isRegistros() == false) {
            lls.setSelected(true);
            jComboBox1.setSelectedIndex(0);
            jDCrearCampo.setModal(true);
            jDCrearCampo.pack();
            jDCrearCampo.setLocationRelativeTo(null);
            jDCrearCampo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(jMenu1, "No se pueden agregar mas campos ya que hay registros existentes");
        }
    }//GEN-LAST:event_jMenuItemNuevoCampoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jDCrearCampo.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItemNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoArchivoActionPerformed
        archivo = new Archivo();
        openfile = true;
        archivo_nuevo = true;
        ArchivoAbierto();
        GuardarArchivo();
        JOptionPane.showMessageDialog(null, "El archivo fue creado exitósamente");
    }//GEN-LAST:event_jMenuItemNuevoArchivoActionPerformed

    private void jMenuItemListarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarCamposActionPerformed
        // TODO add your handling code here
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Campo");
        tabla.addColumn("Tipo");
        tabla.addColumn("Longitud");
        Object[] fila = new Object[3];
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            fila[0] = archivo.getListaCampos().get(i).nombre;
            fila[1] = archivo.getListaCampos().get(i).tipo;
            fila[2] = archivo.getListaCampos().get(i).longitud;
            tabla.addRow(fila);
        }
        jTable1.setModel(tabla);

    }//GEN-LAST:event_jMenuItemListarCamposActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("./Files"));
        FileNameExtensionFilter data = new FileNameExtensionFilter("ABC FILE", "abc");
        fileChooser.setFileFilter(data);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                if (fileChooser.getFileFilter().getDescription().equals("ABC FILE")) {
                    archivo = new Archivo(fileChooser.getSelectedFile().getPath());
                    archivo.cargarArchivo();
                    JOptionPane.showMessageDialog(null, "El archivo se abrio exitósamente");
                    openfile = true;
                    archivo_nuevo = false;
                    ArchivoAbierto();
                    MostrarRegistros();
                    ck.setText(archivo.getNombrellave());
                } else {
                    JOptionPane.showMessageDialog(this, "Solo puede crear archivos ABC");
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Le gustaría guardar los cambios realizados al archivo?", "Alerta", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION && archivo.isSaved()) {
            GuardarArchivo();
            archivo = null;
            openfile = false;
            ArchivoAbierto();
        } else {
            JOptionPane.showMessageDialog(this, "El archivo se cerró con éxito");
            archivo = null;
            openfile = false;
            ArchivoAbierto();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        ck.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        String registro;
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            registro = JOptionPane.showInputDialog("Ingrese el " + archivo.getListaCampos().get(i) + ":\n Tipo: " + archivo.getListaCampos().get(i).getTipo() + ":\n Longitud: " + archivo.getListaCampos().get(i).longitud);
            archivo.getListaCampos().get(i).addRegistro(registro);
        }
        JOptionPane.showMessageDialog(this, "El registro ha sido agregado con éxito");
        archivo.setRegistros(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        GuardarArchivo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemModificarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarCamposActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Campo");
        tabla.addColumn("Tipo");
        Object[] fila = new Object[2];
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            fila[0] = archivo.getListaCampos().get(i).nombre;
            fila[1] = archivo.getListaCampos().get(i).tipo;
            tabla.addRow(fila);
        }
        jTable2.setModel(tabla);
        jDModificarCampo.setModal(true);
        jDModificarCampo.pack();
        jDModificarCampo.setLocationRelativeTo(null);
        jDModificarCampo.setVisible(true);
    }//GEN-LAST:event_jMenuItemModificarCamposActionPerformed

    private void jMenuItemBorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarCamposActionPerformed
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Campo");
        tabla.addColumn("Tipo");
        Object[] fila = new Object[2];
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            fila[0] = archivo.getListaCampos().get(i).nombre;
            fila[1] = archivo.getListaCampos().get(i).tipo;
            tabla.addRow(fila);
        }
        jTable3.setModel(tabla);
        jDBorrarCampo.setModal(true);
        jDBorrarCampo.pack();
        jDBorrarCampo.setLocationRelativeTo(null);
        jDBorrarCampo.setVisible(true);

    }//GEN-LAST:event_jMenuItemBorrarCamposActionPerformed

    private void jMenuItemModificarCamposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItemModificarCamposKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemModificarCamposKeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tabla = new DefaultTableModel();
        try {
            if (evt.isMetaDown()) {
                PopMenuModificar.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione algo antes de dar click derecho");
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jMenuModificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarCampoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabla = new DefaultTableModel();
        archivo.setNombre(JOptionPane.showInputDialog("Ingrese el nuevo nombre"));
        tabla.addColumn("Campo");
        tabla.addColumn("Tipo");
        Object[] fila = new Object[2];
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            fila[0] = archivo.getListaCampos().get(i).nombre;
            fila[1] = archivo.getListaCampos().get(i).tipo;
            tabla.addRow(fila);
        }
        jTable2.setModel(tabla);
        JOptionPane.showMessageDialog(jDModificarCampo, "Modificado con exito la tarea");
    }//GEN-LAST:event_jMenuModificarCampoActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if (!archivo.getListaCampos().isEmpty()) {
            if (!archivo.getListaCampos().get(0).getRegistros().isEmpty()) {
                MostrarRegistros();
            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if (!archivo.getListaCampos().isEmpty()) {
            if (!archivo.getListaCampos().get(0).getRegistros().isEmpty()) {
                DefaultComboBoxModel dml = new DefaultComboBoxModel();
                int aux = 0;
                for (int i = 0; i < archivo.getListaCampos().size(); i++) {
                    if (archivo.getListaCampos().get(i).isLlavePrimaria() == true) {
                        aux = i;
                    }
                }
                for (int i = 0; i < archivo.getListaCampos().get(aux).getRegistros().size(); i++) {
                    dml.addElement(archivo.getListaCampos().get(aux).getRegistro(i));
                }
                jCBRegistros.setModel(dml);
                jDBorrarRegistro.setModal(true);
                jDBorrarRegistro.pack();
                jDBorrarRegistro.setLocationRelativeTo(null);
                jDBorrarRegistro.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "NO hay registros");
                archivo.setRegistros(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay campos creados");
        }
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButtonBorrarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarRegistroMouseClicked
        int temp = jCBRegistros.getSelectedIndex();
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            archivo.getListaCampos().get(i).getRegistros().remove(temp);
        }
        JOptionPane.showMessageDialog(this, "El registro se eliminó con éxito");
        jDBorrarRegistro.setVisible(false);
        MostrarRegistros();
    }//GEN-LAST:event_jButtonBorrarRegistroMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jDBorrarRegistro.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void NuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoNombreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!"".equals(NuevoNombre.getText())) {
            String aux = NuevoNombre.getText();
            archivo.getListaCampos().get(flag).setNombre(aux);
            DefaultTableModel tabla = new DefaultTableModel();
            tabla.addColumn("Campo");
            Object[] fila = new Object[1];
            for (int i = 0; i < archivo.getListaCampos().size(); i++) {
                fila[0] = archivo.getListaCampos().get(i).nombre;
                tabla.addRow(fila);
            }
            jTable2.setModel(tabla);
            jDModificar.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(jDModificar, "Debe seleccionar un nombre valido");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        try {
            flag = jTable2.getSelectedRow();
            if (flag != -1) {
                DefaultTableModel tabla = new DefaultTableModel();
                tabla = (DefaultTableModel) jTable2.getModel();
                String aux = (String) tabla.getValueAt(flag, 0);
                nombreactual.setText(aux);
                jDModificar.setModal(true);
                jDModificar.pack();
                jDModificar.setLocationRelativeTo(null);
                jDModificar.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(jDModificar, "Debe seleccionar un campo de la lista");
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        try {
            flag = jTable3.getSelectedRow();
            if (flag != -1) {
                archivo.getListaCampos().remove(flag);
                JOptionPane.showMessageDialog(jDBorrarCampo, "Se ha borrado el campo exitosamente");
                DefaultTableModel tabla = new DefaultTableModel();
                tabla = (DefaultTableModel) jTable3.getModel();
                tabla.addColumn("Campo");
                Object[] fila = new Object[1];
                for (int i = 0; i < archivo.getListaCampos().size(); i++) {
                    fila[0] = archivo.getListaCampos().get(i).nombre;
                    tabla.addRow(fila);
                }
                jTable3.setModel(tabla);
                jDBorrarCampo.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(jDBorrarCampo, "Debe seleccionar un campo de la lista");
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_jButton5MouseClicked

    public void ArchivoAbierto() {
        jMenuCampos.setEnabled(openfile);
        jMenu1.setEnabled(openfile);
        jMenu2.setEnabled(openfile);
        jMenu3.setEnabled(openfile);
        jMenuItem2.setEnabled(openfile);
        jMenuItem3.setEnabled(openfile);
    }

    public void GuardarArchivo() {
        if (archivo_nuevo) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("./"));
            FileNameExtensionFilter data = new FileNameExtensionFilter("ABC FILE", "abc");
            fileChooser.setFileFilter(data);
            int seleccion = fileChooser.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                try {
                    if (fileChooser.getFileFilter().getDescription().equals("ABC FILE")) {
                        archivo.setPath(fileChooser.getSelectedFile().getPath());
                        archivo.escribirArchivo();
                        archivo_nuevo = false;
                        JOptionPane.showMessageDialog(null, "El archivo fue guardado exitósamente");
                        archivo.setSaved();
                    } else {
                        JOptionPane.showMessageDialog(this, "Solo puede guardar archivos ABC");
                    }
                } catch (Exception e) {

                }
            }
        } else {
            archivo.escribirArchivo();
            JOptionPane.showMessageDialog(this, "El archivo se guardó con éxito");
        }
    }

    public void MostrarRegistros() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        DefaultTableModel tabla = new DefaultTableModel();
        for (int i = 0; i < archivo.getListaCampos().size(); i++) {
            tabla.addColumn(archivo.getListaCampos().get(i));
        }
        Object[] fila = new Object[tabla.getColumnCount()];
        int cont = 0;
//        for (int i = 0; i < archivo.getListaCampos().get(0).getRegistros().size(); i++) {
//            if (tabla.getColumnCount() - 1 == cont) {
//                fila[cont] = archivo.getListaCampos().get(i).getRegistro(cont);
//                tabla.addRow(fila);
//                cont = 0;
//            } else {
//                fila[cont] = archivo.getListaCampos().get(i).getRegistro(cont);
//                cont++;
//            }
//        }
        for (int i = 0; i < archivo.getListaCampos().get(0).getRegistros().size(); i++) {
            for (int j = 0; j < archivo.getListaCampos().size(); j++) {

                fila[j] = archivo.getListaCampos().get(j).getRegistro(i);

            }
            tabla.addRow(fila);
        }
        jTable1.setModel(tabla);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NuevoNombre;
    private javax.swing.JPopupMenu PopMenuModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel ck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBorrarRegistro;
    private javax.swing.JButton jButtonGuardarCampo;
    private javax.swing.JComboBox<String> jCBRegistros;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDBorrarCampo;
    private javax.swing.JDialog jDBorrarRegistro;
    private javax.swing.JDialog jDCrearCampo;
    private javax.swing.JDialog jDModificar;
    private javax.swing.JDialog jDModificarCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCampos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemBorrarCampos;
    private javax.swing.JMenuItem jMenuItemListarCampos;
    private javax.swing.JMenuItem jMenuItemModificarCampos;
    private javax.swing.JMenuItem jMenuItemNuevoArchivo;
    private javax.swing.JMenuItem jMenuItemNuevoCampo;
    private javax.swing.JMenuItem jMenuModificarCampo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel llaveps;
    private javax.swing.JRadioButton llp;
    private javax.swing.JRadioButton lls;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nombreactual;
    // End of variables declaration//GEN-END:variables
    Archivo archivo;
    Campo nodo_campo;
    boolean openfile;
    boolean archivo_nuevo;
    int flag;
}
